name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - name: Unit tests
        run: npm t
      - name: Demo 1
        run: npm run demo1
      - name: Demo 2 with file mask
        run: npm run demo-mask
      - name: Demo 3 saves deps.json file
        run: npm run demo-save
      - name: Demo 3 prints timing
        run: npm run demo-time
      # - name: Check dependencies
      #   run: npm audit --report --omit dev

  release:
    needs: [test]
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install only the semantic release 📦
        run: npm install semantic-release

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
